name: Say Hello World
on:
  issues:
    types: opened
  workflow_dispatch:
   
jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Sample Authentication
        id: Appauth
        uses: Pragadeeshwar/Sample-Probot-App3@master
        with:
          privatekey: ${{secrets.APP_ID}}
          appid: 181303
          baseurl: https://github.com/Pragadeeshwar
          installationid: 24182561
      - uses: Pragadeeshwar/Sample-Probot-App3@master
        id: Sample-Probot-App3
        env:
           token: ${{steps.Appauth.outputs.token}}